"""Sensor-layout and force-classification constants the piezo engine needs.

Single definition: the app-side ``constants/shear.py`` re-exports these, so the
engine never imports from outside ``core/piezo_engine``.
"""

SHEAR_POSITION_CENTER = "C"
SHEAR_POSITION_LEFT = "L"
SHEAR_POSITION_RIGHT = "R"
SHEAR_POSITION_TOP = "T"
SHEAR_POSITION_BOTTOM = "B"
SHEAR_SENSOR_POSITIONS = (
    SHEAR_POSITION_CENTER,
    SHEAR_POSITION_LEFT,
    SHEAR_POSITION_RIGHT,
    SHEAR_POSITION_TOP,
    SHEAR_POSITION_BOTTOM,
)
SHEAR_OUTER_SENSOR_POSITIONS = (
    SHEAR_POSITION_LEFT,
    SHEAR_POSITION_RIGHT,
    SHEAR_POSITION_TOP,
    SHEAR_POSITION_BOTTOM,
)

SHEAR_ZERO_VALUE = 0.0
SHEAR_DEFAULT_ANGLE_DEG = 0.0

SHEAR_FORCE_TYPE_COMPRESSION = "compression"
SHEAR_FORCE_TYPE_TENSION = "tension"
SHEAR_FORCE_TYPE_NONE = "none"
NORMAL_FORCE_SENSOR_COUNT = len(SHEAR_SENSOR_POSITIONS)
NORMAL_FORCE_DENOMINATOR_EPSILON = 1e-12
DEFAULT_NORMAL_FORCE_SENSOR_SPACING_MM = 1.75
